apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup-cron-job
spec:
  #Cron Time is set according to server time, ensure server time zone and set accordingly.
  schedule: "0 8,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgresql-backup-job
              image:
              env:
                - name: BACKUP_PATH
                  value: "/nfs/backup/postgres"
                - name: PG_HOSTNAME
                  value: "postgres-svc.dbs.svc.cluster.local"
                - name: PG_PORT
                  value: "5432"
                - name: PG_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: DB_PASSWORD
                - name: PG_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: DB_USER
              imagePullPolicy: Always
              args:
                - /bin/bash
                - -c
                - cd /home/root; ls; bash postgres-backup.sh;
          restartPolicy: OnFailure
      backoffLimit: 3
