apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  hostPath:
    path: /media/storage/nextcloud
