apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
  volumeName: nextcloud-pv
