apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bitwarden.home.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitwarden-svc
                port:
                  number: 80
