apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  volumeName: bitwarden-pv
