apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  hostPath:
    path: /media/storage/pihole/etc-pihole
