apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: client
    protocol: UDP
    port: 67
    targetPort: 67
  selector:
    app: pihole
