apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: 53
  - name: pihole-http
    port: 8089
    protocol: TCP
    targetPort: 80
  selector:
    app: pihole
