apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: dns
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns-udp
  - name: pihole-http
    port: 80
    nodePort: 30007
    protocol: TCP
    targetPort: pihole-http
  selector:
    app: pihole
  sessionAffinity: None
  type: NodePort
