apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    app: pihole
spec:
  ports:
    - port: 53
      protocol: TCP
      targetPort: 53
    - port: 53
      protocol: UDP
      targetPort: 53
    - port: 8089
      protocol: TCP
      targetPort: 80
  clusterIP: None
  selector:
    app: pihole
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  serviceName: pihole
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: pihole-etc
              mountPath: /etc
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-pvc
