apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  hostPath:
    path: /media/storage/postgres
