apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
